### ISSUE TITLE
Publish jar with Jaeger all-in-one test container and utility classes

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-analytics-java#36]
https://github.com/jaegertracing/jaeger-analytics-java/tree/master/proto/src/test/java/io/jaegertracing/api_v2

This is helpful to use tracing in e2e tests. It could be moved to a separate module or `test-jar`.

**Comment by vab2048** [comment]
I agree - publishing the module and making it available on maven central would be very helpful.

**Comment by pavolloffay** [comment]
The module has been already created https://github.com/jaegertracing/jaeger-analytics-java/tree/master/testcontainers.

It seems that the latest release failed and the artifacts didn't get in.

**Comment by pavolloffay** [comment]
I have triggered a new release 0.6.0.

**Comment by vab2048** [comment]
What exactly would I add to my gradle build so that I can have access to the jaeger-testcontainers jar?

I've tried `io.jaegertracing:jaeger-testcontainers:0.6.0` but It does not work?

I get `Could not resolve io.jaegertracing:jaeger-testcontainers:0.6.0.` 
Is there a specific repository I should add to the build?

**Comment by pavolloffay** [comment]
The 0.6.0 build also failed. It should be all good with 0.7.0, although it might take a couple of hours to propagate to maven central.

**Comment by vab2048** [comment]
Thanks it all works now
